# Generated by Django 4.1 on 2022-08-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abra', '0002_user_email_delete_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Message',
        ),
    ]
