# Generated by Django 4.1 on 2022-08-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abra', '0004_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
